/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.0 location_mark.glb
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import useBouncePosition from './hooks/useBouncePosition.jsx';

const rangeTarget = [0.6, 1.0];
const yRangeTarget = [0, 0.02];
const FRAME_TO_GO = 60;

const LocationMark = (props) => {


    const { nodes, materials } = useGLTF('/img/location_mark.glb');


    const circleBounceX = useBouncePosition({ close: 0.6, far: 1.0, cycleFrames: 20 });
    const groupBounceY = useBouncePosition({ close: 0, far: 0.02, cycleFrames: 40 });


    return (
        <group {...props} dispose={null}
               position={[props.position.x, props.position.y + groupBounceY, props.position.z]}>
            <pointLight color='#f6f3ea' position={[2, 3, 0]} intensity={0.3}/>
            <mesh geometry={nodes.Circle.geometry}
                  material={materials['Material.002']} position={[0.07, 2.47, 0]}
                  rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.Circle001.geometry} material={materials['Material.003']} position={[0, 2.5, 0]}
                  rotation={[0, 0, -Math.PI / 2]} scale={1.08} />
            <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.004']} position={[0.42, 2.46, 0]}
                  rotation={[0, 0, -Math.PI / 2]} scale={[0.84, 0.18, 0.84]} />
            <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.001']}
                  position={[circleBounceX, 2.46, 0]}
                  rotation={[0, 0, -Math.PI / 2]} scale={[0.92, 0.2, 0.92]} />
        </group>
    );
};

useGLTF.preload('/img/location_mark.glb');

export default LocationMark;
